services:
  ibm-mq:
    image: ibmcom/mq
    container_name: mq-dev
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
    volumes:
      - mq-data:/mnt/mqm
    restart: unless-stopped

volumes:
  mq-data: